### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by EastonWang** [jiyfeng/DPLP#3]
Hello jiyfeng,

I read about this code and the corresponding paper recently. But I have some questions about the evaluation metrics. In the evaluation part, you first calculate the precision and recall for each individual document and then take average over all the precisions and recalls like this:

<pre><code>for level in self.levels:
     if 'span' == level:
         p = numpy.array(self.span_perf.percision).mean()
         r = numpy.array(self.span_perf.recall).mean()
         f1 = (2 * p * r) / (p + r)
         print 'F1 score on span level is {0:.4f}'.format(f1)
</code></pre>

This is different from what I thought it to be. I thought it should calculate a global precision and recall instead of using average. So is this a common practice for discourse parsing or just a mistake?

Thanks!

**Comment by jiyfeng** [comment]
The F-score calculated by this code is Macro-average F-score, which has been popularly used in prior work, like (Hernault et al., 2010)
